version: "3.9"
services:
  db:
    image: postgres:16
    container_name: vitalis_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vitalis
      POSTGRES_PASSWORD: vitalis
      POSTGRES_DB: vitalis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
